### ISSUE TITLE
i think you forget prefix?

### ISSUE THREAD

**Issue by alonalibarmn** [Sushipie/Cordbot#1]

**Comment by alonalibarmn** [comment]
so i made a fix plz update it in the files for everyone 
{
  "token": "your_token_here",
  "tenorKey": "your_tenor_API_key_here",
  "prefix": "your_prefix_here"
}

**Comment by Sushipie** [comment]
Thanks for that. I forgot to add the prefix in the config.json requirement. I have updated it now.
